### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by Oviglo** [kylekatarnls/vicopo#1]
Bonjour, quand je fais un appel ajax sur le lien: 'http://vicopo.selfbuild.fr/code/' j'ai un message d'erreur:
Access-Control-Allow-Origin

Avez-vous une solution pour contourner ce problème ? merci.

**Comment by kylekatarnls** [comment]
Bonjour, nous envoyons :
```
Access-Control-Allow-Headers:X-Requested-With
Access-Control-Allow-Methods:GET
Access-Control-Allow-Origin:*
Access-Control-Max-Age:1728000
```

Ce qui autorise toutes les origines.
Pouvez-vous vérifier que vous utilisez bien la méthode GET et que votre page est en http://, si elle est en https://, utilisez l'URL https://www.selfbuild.fr/vicopo/code/.

En cas de doute, vous pouvez me donnez un lien vers la page où vous tentez d'implémenter Vicopo.

**Comment by kylekatarnls** [comment]
Bonjour,

Je me permets de supposer que votre problème est résolu tenu compte du délai écoulé d'une semaine et de clore votre issue.

Cordialement,
