### ISSUE TITLE
Page avec plusieurs champs CP + ville

### ISSUE THREAD

**Issue by alexclub** [kylekatarnls/vicopo#12]
Bonjour,

Tout d'abord, merci pour ce super projet!
Ce n'est pas vraiment un problème mais plus un blocage de ma part.
J'ai un formulaire avec plusieurs fois le duo CP + ville. (En fait l'utilisateur peut rentrer plusieurs adresses en cliquant sur un bouton qui à chaque fois va créer un set de champs: adresse, cp, ville...)
J'ai fait en sorte que le premier duo CP + ville utilise bien les id #city et #code et pas de soucis.
Pour les autres, j'ai fait en sorte qu'ils soient:
#city1 - #code1
#city2 - #code2
....

En partant du script de la démo, je n'arrive pas à modifier la partie suivant qui si j'ai bien compris va faire les requêtes:

    $.each(['code' + thisid, 'city' + thisid], function (i, _name) {
        _name_req = _name.substring(0, 4); 
        console.log(_name + " - " + _name_req);
        var _input = $('#' + _name).on('keyup', function () {
            var _val = _input.val();
            if (_val.length > 1) {
                _cache[_name] = _cache[_name] || {};
                if (_cache[_name][_val]) {
                    _done(_cache[_name][_val]);
                }
                var _data = {};
                _data[_name] = _val;
                $.getJSON(_host, _data, function (_answear) {
                    _cache[_name_req][_answear.input] = _answear.cities;
                    if (_input.val() == _answear.input) {
                        _done(_answear.cities);
                    }
                });
            }
        });
    });

**Comment by kylekatarnls** [comment]
Bonjour,

Vous me dîtes ce que vous avez fait mais pas ce que vous voulez obtenir. Je prends donc l'hypothèse que vous avez réussit à faire fonctionner un couple cp-ville avec ce code mais pas les suivants. Si ce n'est pas ça, merci de détailler le comportement attendu par votre code et le comportement constaté.

Si vous ajoutez les champs en JS (ou jQuery), vous devez alors appeler le script VICOPO à ce moment-là, ça n'est pas un problème propre à VICOPO, le code `$('#' + _name).on('keyup'` doit être exécuté lorsque l'élément existe. Si vous exécutez `$('#city2').on(...` suivi de n'importe quoi et que l'id city2 n'existe pas encore dans la page, le code n'aura alors aucun effet. Pour vérifier ça, vous pouvez logger: `console.log($('#' + _name).length);` qui vous renverra le nombre d'élément trouvé par jQuery, si vous avez 0, alors vous attacher un événement sur 0 éléments : rien ne se passe. Si c'est ça, vous devez alors créer une fonction qui prend en paramètre ce que vous avez nommé `thisid` et appeler cette fonction après la création des champs d'adresse.

**Comment by alexclub** [comment]
Merci pour votre réponse Kyle.

En effet, j'ai lors du chargement de la page 4 champs:
<input type="text" id="code">
<input type="text" id="city">

<input type="text" id="code1">
<input type="text" id="city1">

Puis, je génère les duos suivants en js en incrémentant leur id de 1 à chaque fois.
<input type="text" id="code2"><input type="text" id="city2">
<input type="text" id="code3"><input type="text" id="city3">

Avec le fichier index.js de la démo, j'arrive bien à faire fonctionner vicopo sur les champs:
<input type="text" id="code">
<input type="text" id="city">

mais pas les champs:
<input type="text" id="code1">
<input type="text" id="city1">

Je ne suis pas très expérimenté en jquery mais j'ai supposé que cela était du à la ligne suivante ou les ID sont spécifiés:
var _code = $('#code'), _city = $('#city'), _out = $('#output');

Afin de prendre en compte les variantes d'id (code1, city1, code2, city2...)
J'ai essayé de manipuler les ID en surveillant les events de champs codepostal:

$('[id^=code]').keypress(function (e){
    var thisid = $(this).attr('id');
    var thisid = thisid.substring(4);
    var codeid = '#code' + thisid;
    var cityid = '#city' + thisid;
    var outid = '#output' + thisid;
    console.log(cityid + " - " + outid);

    var _code = $(codeid), _city = $(cityid), _out = $(outid);

    var _cache = {};
    var _protocol = ~(location.protocol + '').indexOf('s') ? 'https' : 'http';
    var _host = _protocol + '://vicopo.selfbuild.fr';
    _code.keyup(function () {
        var _val = $(this).val();
        if (/^[^0-9]/.test(_val)) {
            _code.val('');
            _city.val(_val).focus().trigger('keyup');
        }
    });
    _city.keyup(function () {
        var _val = $(this).val();
        if (/^[0-9]/.test(_val)) {
            _city.val('');
            _code.val(_val).focus().trigger('keyup');
        }
    });
    function _done(_cities) {
        _out.html(_cities.map(function (_data) {
            return '<a href="#">' + _data.code + ' &nbsp; ' + _data.city + '</a>';
        }).join(''));
    }

    $.each(['code' + thisid, 'city' + thisid], function (i, _name) {
        var _name_req = _name.substring(0, 4); 
        console.log(_name + " - " + _name_req);
        var _input = $('#' + _name).on('keyup', function () {
            var _val = _input.val();
            if (_val.length > 1) {
                _cache[_name] = _cache[_name] || {};
                if (_cache[_name][_val]) {
                    _done(_cache[_name_req][_val]);
                }
                var _data = {};
                _data[_name] = _val;
                $.getJSON(_host, _data, function (_answear) {
                    _cache[_name_req][_answear.input] = _answear.cities;
                    if (_input.val() == _answear.input) {
                        _done(_answear.cities);
                    }
                });
            }
        });
    });
    $(document).on('click', '#output' + thisid +' a', function (e) {
        var _contents = $(this).text();
        var _space = _contents.indexOf(' ');
        if (~_space) {
            _code.val(_contents.substr(0, _space));
            _city.val(_contents.substr(_space).trim());
            _out.empty();
        }
        e.preventDefault();
        e.stopPropagation();
        return false;
    });

});

});

Seulement, les requêtes sont passées avec le paramètre 'code1' au lieux de 'code':
Failed to load http://vicopo.selfbuild.fr/?code1=75: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://monsite.fr' is therefore not allowed access.

Merci encore.

**Comment by kylekatarnls** [comment]
OK, le problème, c'est que vous utilisez code1 pour l'id mais aussi pour le paramètre de requête, seuls vos ids sont dynamique, les paramètre envoyés en HTTP sont toujours "code" ou "city".

```js
$('[id^=code]').keypress(function (e) {
    var thisid = $(this).attr('id');
    var thisid = thisid.substring(4);
    var codeid = '#code' + thisid;
    var cityid = '#city' + thisid;
    var outid = '#output' + thisid;

    var _code = $(codeid), _city = $(cityid), _out = $(outid);

    var _cache = {};
    var _protocol = ~(location.protocol + '').indexOf('s') ? 'https' : 'http';
    var _host = _protocol + '://vicopo.selfbuild.fr';
    _code.keyup(function () {
        var _val = $(this).val();
        if (/^[^0-9]/.test(_val)) {
            _code.val('');
            _city.val(_val).focus().trigger('keyup');
        }
    });
    _city.keyup(function () {
        var _val = $(this).val();
        if (/^[0-9]/.test(_val)) {
            _city.val('');
            _code.val(_val).focus().trigger('keyup');
        }
    });

    function _done(_cities) {
        _out.html(_cities.map(function (_data) {
            return '<a href="#">' + _data.code + ' &nbsp; ' + _data.city + '</a>';
        }).join(''));
    }

    $.each(['code', 'city'], function (i, _name) {
        var _input = $('#' + _name + thisid).on('keyup', function () {
            var _val = _input.val();
            if (_val.length > 1) {
                _cache[_name] = _cache[_name] || {};
                if (_cache[_name][_val]) {
                    _done(_cache[_name][_val]);
                }
                var _data = {};
                _data[_name] = _val;
                $.getJSON(_host, _data, function (_answear) {
                    _cache[_name][_answear.input] = _answear.cities;
                    if (_input.val() == _answear.input) {
                        _done(_answear.cities);
                    }
                });
            }
        });
    });
});
$(document).on('click', '#output' + thisid + ' a', function (e) {
    var _contents = $(this).text();
    var _space = _contents.indexOf(' ');
    if (~_space) {
        _code.val(_contents.substr(0, _space));
        _city.val(_contents.substr(_space).trim());
        _out.empty();
    }
    e.preventDefault();
    e.stopPropagation();
    return false;
});
```

**Comment by alexclub** [comment]
Super, ça fonctionne.
Il ne me reste plus qu'à gérer les champs ajoutés en js.

Merci!
