### ISSUE TITLE
API Down

### ISSUE THREAD

**Issue by launay12u** [kylekatarnls/vicopo#13]
Bonjour, j'utilise votre API pour un de mes sites web mais actuellement l'api ne fonctionne plus, j'ai toujours une erreur 500,
Êtes-vous au courant ? 

Cela est-il permanant ou non ?

Cordialement Guillaume Launay

**Comment by kylekatarnls** [comment]
Base de données redémarré, des connexions semblaient mal fermés, peut-être une surcharge, j'inspecte.
