### ISSUE TITLE
API indisponible

### ISSUE THREAD

**Issue by NicolasFR** [kylekatarnls/vicopo#15]
Bonsoir,
Quand on souhaite accéder à http://vicopo.selfbuild.fr/ on obtient le message suivant : Le délai d’attente est dépassé
Merci pour votre travail.
Cordialement
Nicolas

**Comment by kylekatarnls** [comment]
Bonjour, je vous confirme que nous avons eu 2 interruptions de services de 50 min et 52 min dû à des coupures du réseau dans la journée d'hier. Le problème est résolu, désolé pour le dérangement. C'est un incident isolé, notre taux de disponibilité sur l'année dépassant les 99.9%.
Cordialement,

**Comment by NicolasFR** [comment]
Je sais bien, c’était juste pour vous le signaler.
On s’en est rendu compte en pleine mise en production. 
Bon courage.
Cordialement,
