### ISSUE TITLE
Communes nouvelles

### ISSUE THREAD

**Issue by Bartiff** [kylekatarnls/vicopo#17]
Bonjour,

Est-il prévu une mise à jour de votre base avec les communes nouvelles ?
Merci

Bartiff

**Comment by kylekatarnls** [comment]
La base est censée être mise à jour toutes les semaines avec l'INSEE :
http://public.opendatasoft.com/explore/dataset/correspondance-code-insee-code-postal/download/?format=csv

Pouvez-vous me donner la/les villes manquantes que vous avez remarquées ?

**Comment by Bartiff** [comment]
Merci pour votre réponse rapide. 
Je travaille avec les départements 35, 22, 56, 29 et 44 principalement et je ne trouve les villes suivantes :

35360 LA CHAPELLE DU LOU DU LAC
35480 GUIPRY MESSAC
56500 EVELLYS
56460 VAL D'OUST
56450 THEIX NOYALO
44150 VAIR SUR LOIRE
22330 LE MENE

**Comment by kylekatarnls** [comment]
Cette URL n'est visiblement pas mise à jour et date de 2013, la liste faisant fois est a priori celle de 2015 :
https://public.opendatasoft.com/explore/dataset/code-postal-code-insee-2015/export/

Vous pouvez voir que les villes que vous avez citées y sont toutes (et sont donc toutes désormais dans Vicopo).

**Comment by Bartiff** [comment]
Ce matin est regardant de plus prêt je constate que les villes dans la mise à jour de 2015 sont écrites sans les tirets et avec le diminutif ST au lieu de SAINT ...
Est-ce normal ?

**Comment by Bartiff** [comment]
En fait si je prends le lien que vous avez fourni plus haut je vois dans l'onglet tableau qu'il faudrait mieux récupérer la colonne _NOM_COM_ plutôt que la colonne _Nom_commune_ non ?
https://public.opendatasoft.com/explore/dataset/code-postal-code-insee-2015/table/

**Comment by kylekatarnls** [comment]
Il semblerait car La Poste utilise aussi la notation raccourcie dans sa base officielle :
https://datanova.laposte.fr/explore/dataset/laposte_hexasmal/export/?disjunctive.code_commune_insee&disjunctive.nom_de_la_commune&disjunctive.code_postal&disjunctive.libell_d_acheminement&disjunctive.ligne_5
