### ISSUE TITLE
Je ne trouve pas certaines villes

### ISSUE THREAD

**Issue by mapoub** [kylekatarnls/vicopo#18]
Bonjour,

Je viens de constater  que je ne trouve pas Brest ( 29200)  :  
Y a t'il quelque chose que je fais mal ?

Https://vicopo.selfbuild.fr/code/29200   -> {"input":"29200","cities":[]}

https://vicopo.selfbuild.fr/cherche/brest -> {"input":"brest","cities":[{"code":27350,"city":"BRESTOT"}]}

https://vicopo.selfbuild.fr/cherche/292 ->
{"input":"292","cities":[{"code":29260,"city":"LANARVILY"},{"code":29260,"city":"PLOUIDER"},{"code":29260,"city":"LOC BREVALAIRE"},{"code":29260,"city":"TREGARANTEC"},{"code":29260,"city":"PLOUDANIEL"},{"code":29260,"city":"KERNILIS"},{"code":29260,"city":"ST FREGANT"},{"code":29260,"city":"ST MEEN"},{"code":29260,"city":"LESNEVEN"},{"code":29260,"city":"LE FOLGOET"},{"code":29260,"city":"KERNOUES"},{"code":29250,"city":"SANTEC"},{"code":29250,"city":"ST POL DE LEON"},{"code":29250,"city":"PLOUGOULM"},{"code":29250,"city":"SIBIRIL"},{"code":29280,"city":"PLOUZANE"},{"code":29280,"city":"LOCMARIA PLOUZANE"},{"code":29253,"city":"ILE DE BATZ"},{"code":29290,"city":"GUIPRONVEL"},{"code":29290,"city":"ST RENAN"},{"code":29290,"city":"LANRIVOARE"},{"code":29290,"city":"TREOUERGAT"},{"code":29290,"city":"MILIZAC"},{"code":29246,"city":"POULLAOUEN"},{"code":29270,"city":"ST HERNIN"},{"code":29270,"city":"CLEDEN POHER"},{"code":29270,"city":"KERGLOFF"},{"code":29270,"city":"CARHAIX PLOUGUER"},{"code":29270,"city":"MOTREFF"},{"code":29270,"city":"PLOUNEVEZEL"},{"code":29233,"city":"CLEDER"},{"code":29252,"city":"PLOUEZOC H"},{"code":29241,"city":"LOCQUIREC"},{"code":29242,"city":"OUESSANT"},{"code":29217,"city":"TREBABU"},{"code":29217,"city":"PLOUGONVELIN"}]}

Cdt

**Comment by kylekatarnls** [comment]
Bonjour, nous avons changé récemment de base de données de l'INSEE pour prendre en compte les nouvelles villes.

En attendant de voir pourquoi il y manque des villes et/ou de changer de base, j'ai fusionné les 2. Brest est à nouveau présente.
