### ISSUE TITLE
saint / st

### ISSUE THREAD

**Issue by finevine** [kylekatarnls/vicopo#19]
Bonjour, cette api est extra.
Je suis débutant en prog. Je ne sais pas s'il serait possible de l'améliorer en permettant de rechercher les ville Saint-Truc pour renvoyer St-Truc.
Actuellement la recherche de ville qui commence par `Saint` ne fonctionne pas, il faut entrer `St`.
Encore merci

**Comment by kylekatarnls** [comment]
Bonjour,

Bonne idée, j'ai ajouté st = saint dans les substituts de recherche, donc désormais chercher "sainte ju" fait apparaître "ste julie", "sainte juliette" etc. dans la liste.

Merci,
