### ISSUE TITLE
1er exemple

### ISSUE THREAD

**Issue by shirleyseywert** [kylekatarnls/vicopo#2]
Je souhaite utiliser votre 1er exemple de http://vicopo.selfbuild.fr/
Hélas, comme il n'est pas expliqué (et c'est le seul), j'ai beaucoup de difficultés à le mettre en place.
Pourriez-vous donner la marche à suivre?
Merci d'avance

**Comment by kylekatarnls** [comment]
Bonjour,

Voici le code commenté de la barre de démonstration :
https://jsfiddle.net/KyleKatarn/e0cg1t9q/11/

Cordialement,

**Comment by shirleyseywert** [comment]
Merci beaucoup!!! génial !

Est-il possible néanmoins de l'utiliser plusieurs fois sur la même page? 
J'ai cette contrainte dans mon projet actuel :-(

**Comment by kylekatarnls** [comment]
Oui, encapsulez les balises HTML dans un bloc marqué d'une classe par exemple ```vicopo-wrapper```, remplacez les id par des classes à l'intérieur, remplacez les ```#``` par ```.``` dans le code jQuery et iterez sur ```vicopo-wrapper```, ce principe est applicable à n'importe quel code JS appliqué sur du HTML :

```html
<div class="vicopo-wrapper">
  <section>
   <div class="half">
      <input class="code" placeholder="Code postal" autocomplete="off" autofocus>
    </div>
    <div class="half">
      <input class="city" placeholder="Ville" autocomplete="off">
    </div>
    </section>
  <div class="output"></div>
</div>
```

Ci-dessous les parties du code qui changent :
```javascript
jQuery(function ($) {
  $('.vicopo-wrapper').each(function () {
        var _wrapper = this;
	var _code = $('.code', _wrapper), _city = $('.city', _wrapper), _out = $('.output', _wrapper);
	...
        // Appel de Vicopo lors de l'appui sur une touche dans #code ou #city
	$.each(['code', 'city'], function (i, _name) {
		var _input = $('.' + _name, _wrapper).on('keyup', function () {
	...
        // Au clic sur un lien, on remplace la valeur des champs code postal et ville
	$(_wrapper).on('click', '.output a', function (e) {
	...
  });
});
```
