### ISSUE TITLE
Rentrer une ville avec clique gauche au lieu d'entrée

### ISSUE THREAD

**Issue by nolwensheets** [kylekatarnls/vicopo#21]
Bonjour,

J'aimerais valider la ville avec un clique gauche sur la ville souhaitée, plutôt que devoir appuyer sur entrée et sélectionner la première ville. 

Y a t-il un moyen simple d'implémenter cela? Je pense que beaucoup d'utilisateurs pourraient être intéressés.

Merci beaucoup!

**Comment by kylekatarnls** [comment]
Bonjour,

Voici un exemple :
https://jsfiddle.net/KyleKatarn/8sjqo92t/
