### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by nadfri** [kylekatarnls/vicopo#24]
Bonjour,
Je ne sais pas si tu t'occupes encore de ton API, mais depuis peu, j'ai des problemes de CORS blocked, sais tu d'ou peux venir ce problème?

Access to XMLHttpRequest at 'https://www.selfbuild.fr/vicopo?code=77' from origin 'https://couvre-feu.netlify.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Voici le lien de la page ou j'ai implémenté ton API:
https://couvre-feu.netlify.app/newuser

**Comment by kylekatarnls** [comment]
Bonjour, cette URL est incorrect, le domaine est https://vicopo.selfbuild.fr/:

https://vicopo.selfbuild.fr/?code=77
ou
https://vicopo.selfbuild.fr/code/77

Merci,

**Comment by nadfri** [comment]
Merci ca marche nickel!
