### ISSUE TITLE
Code postal town not exist

### ISSUE THREAD

**Issue by tgilbert-consoneo** [kylekatarnls/vicopo#25]
Hello, 

There is a postal code that does not return a city. Yet this city exists with this zip code number.
Can you add this city.

21605 Sennecey-lès-Dijon France

Thank you

**Comment by kylekatarnls** [comment]
Hello,

I think you're mixing the "code postal" and the "code commune". See https://fr.wikipedia.org/wiki/Sennecey-l%C3%A8s-Dijon

Code postal  = 21800
Code commune  =  21605

And so VICOPO find it with "21800" properly.

Thanks,
