### ISSUE TITLE
Certificat SSL expiré

### ISSUE THREAD

**Issue by Vendredi3** [kylekatarnls/vicopo#26]
Bonjour et merci tout d'abord pour ce super boulot.

Le certificat Let's Encrypt est expiré, du coup les appels à partir d'un site https échouent.

![image](https://user-images.githubusercontent.com/7081907/99063626-0c3ba880-25a5-11eb-887d-d9ed7c7a2745.png)

**Comment by nadfri** [comment]
Même problème malheureusement :(

**Comment by kylekatarnls** [comment]
Un problème de mise à jour a rendu le renouvellement automatique inopérant. C'est désormais résolu.

Merci,
