### ISSUE TITLE
Problème accès à l'API

### ISSUE THREAD

**Issue by OLKinG** [kylekatarnls/vicopo#27]
Bonjour,

Je me permets de vous informer concernant un problème d'accès à l'API et surtout d'accès au domaine principal : https://vicopo.selfbuild.fr qui renvoi un erreur "Site inaccessible" ERR_CONNECTION_TIMED_OUT.

![bug-access-site-vicopo](https://user-images.githubusercontent.com/25882632/101343355-2c991300-3884-11eb-98dd-983197f29364.jpg)

**Comment by kylekatarnls** [comment]
Désolé du désagrément, je n'ai pas de réponse de mon hébergeur. Vous pouvez en attendant utiliser le back-up https://vicopo.ovnicap.com/

Merci de votre patience.

**Comment by OLKinG** [comment]
Ok merci le retour rapide et l'url de back-up. 👍

**Comment by kylekatarnls** [comment]
Réparé, je recommande de repasser sur https://vicopo.selfbuild.fr car je vais prochainement utiliser l'autre URL pour tester une prochaine version de l'API et de l'infrastructure qui devrait mieux supporter la charge.

**Comment by OLKinG** [comment]
OK merci.

**Comment by YoJaum33** [comment]
Bonjour et merci pour cette api.

Je me suis rendu compte que depuis quelque jours, quand je rentre un CP ça me renvoi un résultat "erreur". Egalement aussi sur votre site https://vicopo.selfbuild.fr/ concernant la partie "Remplir le champ au clic sur un des choix "
