### ISSUE TITLE
Pas de résultats avec codes postaux Corse

### ISSUE THREAD

**Issue by EroyerBS** [kylekatarnls/vicopo#28]
Bonjour, 
Quand je recherche via un code postal Corse (par exemple 20000 pour Ajaccio ou 20200 pour Batia) je n'ai aucun résultat.
Par contre la recherche par ville fonctionne, j'ai bien les codes postaux qui sont retournés.
Il y a donc un soucis avec tous les codes postaux de la Corse.

Merci

**Comment by kylekatarnls** [comment]
Bonsoir,

Régression corrigée. Merci de l'avoir signalé.

**Comment by EroyerConsoneo** [comment]
Merci
