### ISSUE TITLE
Code postal ne remontant pas la ville 

### ISSUE THREAD

**Issue by tgilbert-consoneo** [kylekatarnls/vicopo#29]
Bonjour,

85600 :  Saint-Hilaire-de-Loulay
Ce code postal n'affiche pas la ville. Est ce que vous pouvez ajouter cette ville ?

https://fr.wikipedia.org/wiki/Saint-Hilaire-de-Loulay

Merci

**Comment by kylekatarnls** [comment]
Comme indiqué sur la page Wikipédia qui vous avez mis en lien:

> Elle fait partie depuis 2019 de la commune de Montaigu-Vendée.

Hors Vicopo met régulièrement à jour sa base de données d'après le registre INSEE. Donc seule les communes ayant actuellement le code postal cherché apparaissent.

Merci.
