### ISSUE TITLE
L'api retourne systématiquement 00000 ERREUR

### ISSUE THREAD

**Issue by floZx** [kylekatarnls/vicopo#30]
Bonjour,
J'utilise l'api sur plusieurs sites et sur certains d'entres eux j'ai systématiquement le retour `00000 ERREUR` depuis le début de semaine. Y a t-il eu des changements sur le serveur qui provoquent ce dysfonctionnement sur ces sites là?

**Comment by kylekatarnls** [comment]
Bonjour,

Je maintiens l'API à mes frais et la charge augmentant, j'ai dû instauré des quotas par IP/par domaine pour les requêtes anonymes afin d'assurer une distribution équitable aux utilisateurs.

Si vous consultez le JSON de l'erreur, vous aurez un message explicatif et un lien vers la procédure à suivre allouer plus de quota.

Cordialement,

**Comment by floZx** [comment]
Je ne peux pas consulter le retour json, pourriez vous me faire parvenir
l'url contenant la procédure à suivre.

D'avance merci.
Cordialement.

**Comment by kylekatarnls** [comment]
Vous pouvez vous inscrire et enregister vos sites web et/ou serveurs via:
https://vicopo.selfbuild.fr/register

Cordialement,
