### ISSUE TITLE
Panne du datacenter / Provider is down

### ISSUE THREAD

**Issue by kylekatarnls** [kylekatarnls/vicopo#31]
Chers utilisateurs, je suis navré de vous relayer cette information :
https://www.ovh.com/fr/news/presse/cpl1785.dernieres-informations-notre-site-strasbourg
Un incendit s'est déclaré chez notre fournisseur d'hébergement.

Dear users I'm sorry to forward :
https://www.ovh.com/fr/news/presse/cpl1785.dernieres-informations-notre-site-strasbourg
A fire started in our provider building

**Comment by kylekatarnls** [comment]
Je suis en train de transformer une version de test sur un serveur de développement qui pourra être utilisé en attendant la résolution d'incident.

**Comment by kylekatarnls** [comment]
https://postal-code.selfbuild.fr/ est disponible en remplacement (remplacer "vicopo.selfbuild.fr" par "postal-code.selfbuild.fr" dans le script).

Souscrivez au notifications de cette issue pour être prévenu du rétablissement.

**Comment by jmsilcom** [comment]
Génial ! merci pour la réactivité

**Comment by jmsilcom** [comment]
J'ai un message d'erreur en console 
`Access to XMLHttpRequest at 'http://postal-code.selfbuild.fr/?code=33' from origin 'http://gyb2c.tunnelv3.lagenceoueb.local' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
jquery.min.js:2 GET http://postal-code.selfbuild.fr/?code=33 net::ERR_FAILED
send @ jquery.min.js:2
ajax @ jquery.min.js:2
s.ajax.s.ajax @ jquery-migrate.min.js:2
S.<computed> @ jquery.min.js:2
getJSON @ jquery.min.js:2
getVicopo @ vicopo.js:1
vicopo @ vicopo.js:1
(anonymous) @ vicopo.js:1
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2`

**Comment by kylekatarnls** [comment]
Hum, très étrange le Access-Control-Allow-Origin est `*` et identique à ce qu'il y avait sur vicopo.selfbuild.fr, j'ai fait un essai sur jsfiddle.net qui est donc aussi un domaine différent et le script peut se lancer : https://jsfiddle.net/KyleKatarn/ygd5m48e/4/

Vous avez bien pris le script https://github.com/kylekatarnls/vicopo/blob/master/api.js (ou la version minifiée) et remplacer à l'intérieur `vicopo.selfbuild.fr` par `postal-code.selfbuild.fr`?

**Comment by jmsilcom** [comment]
Je n'avais pas pris cette version là du coup, ça fonctionne, en effet
Merci bcp

**Comment by kylekatarnls** [comment]
Il a été confirmé par OVH que notre serveur n'était pas récupérable. Nous avons donc réinstallé un nouveau serveur.

L'API et la documentation de https://vicopo.selfbuild.fr ont été réinstallés aujourd'hui.

Nous travaillons à la réconciliation des données pour pouvoir rapidement ré-ouvrir l'espace membre.

**Comment by florancy** [comment]
Merci pour votre réactivité et la mise en place de postal-code.selfbuild.fr.
J'imagine que vous êtes déjà dessus mais l'API répond actuellement avec une 404 not found : https://vicopo.selfbuild.fr/cherche/lyon

**Comment by kylekatarnls** [comment]
Bonjour, en effet, la configuration de réécriture d'URL n'est pas encore fonctionnelle. Vous pouvez utiliser https://vicopo.selfbuild.fr/?search=lyon en attendant.

Je tâcherai de mettre à jour cette issue à chaque étape jusqu'au rétablissement de toutes les fonctionnalités.

**Comment by kylekatarnls** [comment]
Les URLs telles que https://vicopo.selfbuild.fr/cherche/lyon sont à nouveau opérationnelles.

**Comment by kylekatarnls** [comment]
OVH devrait terminer les réinstallations de son côté mardi 30 mars. Nous saurons a cette date si nos backups sont intacts et pourrons alors les restaurer d'ici la fin de la semaine. Dans ce scénario, tous les utilisateurs retrouveront leur compte et leurs domaines/IPs tels qu'avant l'incident.

Si ce n'est pas le cas, un plan B est prêt à être déployé, dans ce scénario, les propriétés avec plus de 1000 requêtes enregistrées avant l'incident et tous les comptes associés à ces propriétés seront restaurées, les utilisateurs recevront un mail récapitulant la restauration de leur compte, un nouveau mot de passe aléatoire (à changer après la première connexion) leur sera attribué.

Dans les 2 scénarios, un délai pour permettre aux utilisateur de vérifier/mettre à jour leur données sera laissé avant la réactivation des compteurs (notamment pour les adresses IP qui auraient changé depuis ou à cause de l'incident chez OVH).

**Comment by kylekatarnls** [comment]
Les données n'ayant pas pu être récupérer, nous avons procéder à une restauration manuelle des comptes payants. Veuillez vérifier votre dossier de spam si vous n'avez pas reçu d'e-mail avec le nouveau mot de passe aléatoire généré. Si vous l'avez supprimé par erreur, ce n'est pas grave, vous pouvez utiliser [la fonction de réinitialisation de mot de passe](https://vicopo.selfbuild.fr/forgot-password).

Nous prions les propriétaires de comptes gratuits de bien vouloir les recréer et vous prions de nous excuser pour la gène occasionnée.

Cordialement,
