### ISSUE TITLE
Code database

### ISSUE THREAD

**Issue by jmsilcom** [kylekatarnls/vicopo#32]
Bonjour,

la liste des codes postaux <-> nom de la commune est associée à quelle base de données ?
On fait une vérification des champs saisis avec apicarto et jquery.validate() de la manière suivante :
`jQuery.validator.addMethod("villeValidator", function(value, element) {
                                    let valid = false;
                                    elements = value.split(' - ');
                                    console.log(elements);
                                        $.ajax({
                                            url : `https://apicarto.ign.fr/api/codes-postaux/communes/${elements[0]}`,
                                            type : 'GET',
                                            dataType : 'json',
                                            async: false,
                                            success : function(response) {
                                                response.forEach(ville => {
                                                    if (ville.libelleAcheminement == elements[1]) {
                                                    console.log("OK")
                                                    valid = true;
                                                }
                                                })
                                            }
                                        });
                                    return valid;
                                });`
                                
 Ça fonctionne bien avec les noms simples, mais avec les noms composé le formulaire ne se valide pas.
 L'hypothèse est la différence entre le nom de commune dans la base vicopo et celui dans la base apicarto.
 A-t-on un autre moyen d'empêcher la validation du champ tant qu'il n'est pas conforme à une association codepostal - ville existante ?
 Merci pour votre aide !

**Comment by kylekatarnls** [comment]
Les noms des villes sur Vicopo apparaissent tels qu'enregistré à l'INSEE, effectivement, des conventions telles que ST pour "Saint", uniformisation des tirets y sont utilisées.

En toute logique, si vous faitez l'autocompletion avec Vicopo, vous devriez faire la validation avec Vicopo également, par exemple en ré-appelant l'API avec le code postal saisi (utilisez le cache de jQuery.ajax pour que cet appel soit instantanné) et en vérifiant que la ville dans le champ est l'un des résultats obtenus.

S'il ne l'est pas, je recommande une comparaison de Leveinstein pour trier les résultats du plus au moins ressemblant et ainsi suggérer à l'utilisateur la ville la plus pertinente en auto-correction :

```js
function levenshte(a, b) {
  if(a.length == 0) return b.length; 
  if(b.length == 0) return a.length; 

  var matrix = [];

  // increment along the first column of each row
  var i;
  for(i = 0; i <= b.length; i++){
    matrix[i] = [i];
  }

  // increment each column in the first row
  var j;
  for(j = 0; j <= a.length; j++){
    matrix[0][j] = j;
  }

  // Fill in the rest of the matrix
  for(i = 1; i <= b.length; i++){
    for(j = 1; j <= a.length; j++){
      if(b.charAt(i-1) == a.charAt(j-1)){
        matrix[i][j] = matrix[i-1][j-1];
      } else {
        matrix[i][j] = Math.min(matrix[i-1][j-1] + 1, // substitution
                                Math.min(matrix[i][j-1] + 1, // insertion
                                         matrix[i-1][j] + 1)); // deletion
      }
    }
  }

  return matrix[b.length][a.length];
}
```

En tous les cas, je ne recommande pas de mélanger plusieurs API

**Comment by kylekatarnls** [comment]
Voici un exemple de ce que je veux dire:
https://jsfiddle.net/KyleKatarn/ntwycok6/35/
Vous pouvez essayer par exemple 87200 avec "SAINT JUNIEN" ou "SAINT MARTIN", la proposition la plus pertinente est alors faite parmi les villes qui correspondent au code postal.
