### ISSUE TITLE
Problème cp qui retourne erreur

### ISSUE THREAD

**Issue by YoJaum33** [kylekatarnls/vicopo#33]
Bonjour et merci pour cette api.

Je me suis rendu compte que depuis quelque jours, quand je rentre un CP ça me renvoi un résultat "erreur". Egalement aussi sur votre site https://vicopo.selfbuild.fr/ concernant la partie "Remplir le champ au clic sur un des choix "

Cordialement

Yoann

**Comment by kylekatarnls** [comment]
Bonjour,

Le plus probable est que votre adresse IP ait atteint son quota maximum. Les requêtes anonymes sont limitées pour éviter des saturations. Inspectez l'erreur en question dans la réponse JSON (par exemple https://vicopo.selfbuild.fr/?code=11111) elle contient un lien d'aide pour enregistrer votre IP et augmenter votre quota.

Cordialement,

**Comment by YoJaum33** [comment]
Oui merci j'ai trouvé et j'ai enregistré mon IP pour les 500 gratuites. C'est top pour finir mon mémoire.

**Comment by YoJaum33** [comment]
J'en suis à 49 sur les 5000 de juin mais ça me retourne quand même toujours erreur quand je tape un code postal

**Comment by kylekatarnls** [comment]
La propriété qui apparait dans le lien d'aide est-elle bien la même que celle que vous avez enregistrée ?

**Comment by YoJaum33** [comment]
Je ne comprends pas votre question mais j'ai enregistré mon IP. Je travaille sous laravel avec la commande "php artisan serve" pour faire fonctioner mon appli pour le moment

**Comment by kylekatarnls** [comment]
Pour tester Vicopo en local ajoutez un alias dans `/etc/hots` (ou `C:\Windows\System32\drivers\etc\hosts` sur Windows) par exemple:

```
127.0.0.1 yojaum33-laravel-app.com
```

Et utilisez `http://yojaum33-laravel-app.com:8080` au lieu de `http://localhost:8080` pour tester les pages de votre site utilisant Vicopo.

Cordialement,
