### ISSUE TITLE
Comment utiliser Vicopo et sa propre base de données ?

### ISSUE THREAD

**Issue by david0613** [kylekatarnls/vicopo#36]
Bonjour,
je vousdrais utiliser ma propre base de villes et code postaux (communes).
Comment faire ?
Je ne suis pas en PDO.

Merci

Ma table :

`-- Structure de la table `communes`
--

CREATE TABLE IF NOT EXISTS `communes` (
  `dc` int(1) NOT NULL DEFAULT '0',
  `clieu` varchar(10) NOT NULL DEFAULT '',
  `reg` int(3) NOT NULL DEFAULT '0',
  `nreg` varchar(100) NOT NULL DEFAULT '',
  `dpt` char(3) NOT NULL DEFAULT '',
  `ndpt` varchar(100) NOT NULL DEFAULT '',
  `com` varchar(5) NOT NULL DEFAULT '0',
  `arr` int(2) NOT NULL DEFAULT '0',
  `cant` int(3) NOT NULL DEFAULT '0',
  `epci` int(9) NOT NULL DEFAULT '0',
  `conj` int(2) NOT NULL DEFAULT '0',
  `cp` varchar(5) NOT NULL DEFAULT '',
  `ncom` varchar(100) NOT NULL DEFAULT '',
  `ancom` varchar(255) NOT NULL DEFAULT '',
  `pop` int(9) NOT NULL DEFAULT '0',
  `popmaj` int(9) NOT NULL DEFAULT '0',
  `alti` int(4) NOT NULL DEFAULT '0',
  `longitude` varchar(20) NOT NULL DEFAULT '0.000000000000000',
  `latitude` varchar(20) NOT NULL DEFAULT '0.000000000000000',
  `surf` float(8,2) NOT NULL DEFAULT '0.00'
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Contenu de la table `communes`
--

INSERT INTO `communes` (`dc`, `clieu`, `reg`, `nreg`, `dpt`, `ndpt`, `com`, `arr`, `cant`, `epci`, `conj`, `cp`, `ncom`, `ancom`, `pop`, `popmaj`, `alti`, `longitude`, `latitude`, `surf`) VALUES
(0, '0', 121, 'Rhône-Alpes', '01', 'Ain', '01001', 2, 10, 240100644, 5, '01400', 'Abergement-Clémenciat', 'l''Abergement-Clémenciat', 818, 787, 257, '4.9191670417786009', '46.15222167968799', 15.70),
(0, '0', 121, 'Rhône-Alpes', '01', 'Ain', '01002', 1, 1, 240100883, 5, '01640', 'Abergement-de-Varey', 'l''Abergement-de-Varey', 201, 207, 367, '5.4238891601562997', '46.007778167725', 9.14),
(0, '1', 121, 'Rhône-Alpes', '01', 'Ain', '01004', 1, 1, 240100883, 1, '01500', 'Ambérieu-en-Bugey', 'Ambérieu-en-Bugey', 13131, 13350, 247, '5.3488888740539995', '45.956111907959006', 24.51),
(0, '0', 121, 'Rhône-Alpes', '01', 'Ain', '01005', 2, 30, 240100735, 1, '01330', 'Ambérieux-en-Dombes', 'Ambérieux-en-Dombes', 1581, 1592, 293, '4.9041671752930007', '45.996112823486008', 16.06),
(0, '0', 121, 'Rhône-Alpes', '01', 'Ain', '01006', 1, 4, 240100354, 1, '01300', 'Ambléon', 'Ambléon', 125, 120, 400, '5.6022219657898003', '45.7502784729', 6.03),
(0, '0', 121, 'Rhône-Alpes', '01', 'Ain', '01007', 1, 1, 240100883, 1, '01500', 'Ambronay', 'Ambronay', 2368, 2328, 250, '5.3594441413878995', '46.008056640625007', 33.64);`

**Comment by kylekatarnls** [comment]
Vous pouvez modifier le script, le meilleur moyen étant de [`fork`](https://github.com/kylekatarnls/vicopo/fork) ce projet. De cette manière vous pouvez régulièrement mettre à jour votre fork, c'est à dire merger avec git les modification faites ici sans écraser vos propres modifications.

A priori la seule modification que vous aurez besoin de faire est de changer l'URL de l'API :
https://github.com/kylekatarnls/vicopo/blob/master/api.js#L7

Vous devez le remplacer par l'URL de votre propre API

Cette route d'API va recevoir `?code=112` ou `?city=Par` et doit retourner un résultat JSON structuré comme suit :
```json
{"input":"745","cities":[
  {"code":11200,"city":"PARAZA"},
  ...
]}
```

Attention toutefois, je ne vois pas d'index dans votre table, hors si vous avez des milliers de villes dans votre table, une recherche par ville/code sans index va charger toute votre table à chaque fois, vous risquez d'avoir des chargements très long de gaspiller beaucoup de ressources.

L'API officielle de Vicopo a de nombreuses optimisations pour lui permettre de supporter la charge et des sécurités pour éviter les DDoS, si votre page ou API est accessible publiquement, vous devrez gérer ces points de votre côté et vont dépendre de votre stack technique.

Sur le papier, il n'y a rien qui empêche d'utiliser une autre API si celle si retourne un résultat compatible, ou même de modifier le script pour supporter une autre structure JSON. C'est techniquement possible et peut se faire en respectant la license MIT. Mais ceci sort du périmètre de la librairie, je ne peux fournir ni garantie ni support sur la partie back-end de ce projet.

J'espère toutefois que ça répond à votre question de manière satisfaisante. Si jamais vous avez besoin de plus d'aide pour votre projet, vous pouvez également me joindre en privé via https://vicopo.selfbuild.fr/contact
