### ISSUE TITLE
Liste toujours visible sur edit

### ISSUE THREAD

**Issue by radiz13** [kylekatarnls/vicopo#37]
Salut,
j'ai un soucis avec la liste :
- fonctionne parfaitement lors de la création de mon entité
- lorsque j’édite mon entité adresse, la liste apparait sur la page à l'ouverture, alors que je ne suis pas entré dans le champ cp ou ville

```
{{ form_row(form.cp) }}
<div id="output">
   <ul class="list-group list-group-flush mb-3" style="margin-top: -1rem !important;">
      <li data-vicopo="#etablissement_ville, #etablissement_cp" data-vicopo-click='{"#etablissement_cp": "code", "#etablissement_ville":"ville"}' class="list-group-item cursor-pointer">
         <strong data-vicopo-code-postal></strong>
         <span data-vicopo-ville></span>
      </li>
   </ul>
</div>
{{ form_row(form.ville) }}

```

**Comment by kylekatarnls** [comment]
Bonjour, je présume que vous avez utilisé l'exemple contenant : `$(_fields).trigger('keyup');`

Cette ligne déclenche un premier appel à Vicopo si jamais le champ n'est pas vide.

À la place de cette ligne utiliser :
```js
$(_fields).vicopoTargets().hide();
```

Pour cacher le template de Vicopo en attendant le premier changement de valeur dans le champ.

https://jsfiddle.net/KyleKatarn/ntwycok6/45/

**Comment by kylekatarnls** [comment]
J'ai également rajouté un attribut HTML:

Vous pouvez également utiliser `data-vicopo-hide-on-start` désormais pour que le résultat initial n'apparaisse pas :
```html
  <li data-vicopo="#ville, #code" data-vicopo-click='{"#code": "code", "#ville": "ville"}' data-vicopo-hide-on-start>
```

**Comment by radiz13** [comment]
Un grand merci, l'attribut `data-vicopo-hide-on-start` est juste parfait !
