### ISSUE TITLE
Probleme pour mon formulaire

### ISSUE THREAD

**Issue by postel5u** [kylekatarnls/vicopo#4]
Bonjour,

Je viens de découvrir vicopo et celà m'interesse beaucoup, mais j'ai un soucis pour appliquer l'exemple classique en remplaceant ul+li par un select et des option (je souhaite faire un formulaire d'inscription).
Le soucis se situe au niveau de l'affichage, comment afficher les noms des villes sans utiliser le span data-vicopo-ville ? Merci d'avance !

**Comment by kylekatarnls** [comment]
Vous pouvez utiliser data-vicopo-val-ville pour remplir un input avec la première valeur. Mais pour un select, vous allez devoir utiliser .vicopo en JS appliqué à un élément jQuery (input du code postal) et le callback qui vous retourne la liste des villes lors de la saisie.

**Comment by postel5u** [comment]
Merci pour la réponse et j'avais oublié de le préciser mais j'ai essayer les fonctions .vicopo mais elle me sort inlassablement cette erreur : TypeError: $(...).vicopo is not a function

**Comment by kylekatarnls** [comment]
Vicopo est un plugin Wordpress, vous devez donc inclure les scripts dans l'ordre suivant sur votre page à la fin de la balise <body> jQuery, Vicopo, votre script qui appelle .vicopo et il faut attendre que le DOM soit chargé en mettant votre script dans l'appel suivant :
`jQuery(function ($) { /* votre code ici */ });`
Je publierai prochainement une version où cet appel ne sera plus nécessaire.

**Comment by postel5u** [comment]
Super tu viens de m'apprendre un truc ! A aucun moment j'ai pensé à attendre le DOM et maintenant ça fonctionne super bien ! Merci beaucoup pour ton aide et ton plugin super pratique !
