### ISSUE TITLE
HTTPS non sécurisé

### ISSUE THREAD

**Issue by launay12u** [kylekatarnls/vicopo#5]
Bonjour, 
Tout d'abord merci pour ton travaille, ton API est très utile est très facile à mettre en place. Mais j'ai un problème, ton certificat https n'est plus valide du coup je ne peux pas intégrer l'API à mon site ... J'aimerais savoir si tu pouvais le renouveler (Let's on crypt le fait gratuitement). 

Merci d'avance pour ta réponse.

**Comment by kylekatarnls** [comment]
Oui, je sais que StartCom a maintenant des problèmes mais les certificats déjà émis sont censés être encore valables. Ce checker valide aussi: https://www.sslshopper.com/ssl-checker.html#hostname=https://vicopo.selfbuild.fr/

La date de ton PC est correcte et tu n'as pas de restrictions CORS de ton côté ? En allant sur le site de vicopo par exemple, le cadenas est vert ? https://vicopo.selfbuild.fr/

**Comment by launay12u** [comment]
Bonjour,
J'ai fais un peux de recherche est j'ai remarqué que cette erreur n'était que sur Google Chrome,
L'erreur : err_cert_authority_invalid. j'ai eu du mal à trouver de la doc mais je sais que je ne suis pas le seul a voir cette erreur sur vicopo.selfbuild.fr (j'ai essayé sur d'autre ordinateur et sur mon téléphone), sur Firefox ou Safari ça fonctionne. Si tu veux je te mets le lien d'un stackoverflow qui parle du même problème mais seulement sur mobile : 
http://stackoverflow.com/questions/27892873/ssl-cert-err-cert-authority-invalid-on-mobile-chrome-only

**Comment by kylekatarnls** [comment]
Merci pour votre aide, je vais donc anticiper le passage à Let's Encrypt. Semaine prochaine normalement.

**Comment by launay12u** [comment]
Super, merci beaucoup pour ta réactivité 👍

**Comment by torzuoliH** [comment]
Même soucis sur Chrome Desktop, mais pas sur Chrome Mobile (iOS).

**Comment by kylekatarnls** [comment]
Salut à tous, Vicopo HTTPS est désormais fourni par Let's Encrypt. Cette autorité est normalement reconnue partout à l'heure actuelle.

**Comment by torzuoliH** [comment]
@kylekatarnls merci, beau travail 😌

**Comment by launay12u** [comment]
Thx
