### ISSUE TITLE
Code commune

### ISSUE THREAD

**Issue by kara71** [kylekatarnls/vicopo#7]
En plus du code postal, il serait pratique de pouvoir obtenir le code commune (unique) par ville.
Dataset par ici > https://public.opendatasoft.com/explore/dataset/correspondance-code-insee-code-postal/

**Comment by kylekatarnls** [comment]
Bonjour, nous utilisons cette même source de données. Notez que désormais opendatasoft.com a sa propre API, ce qui vous permet déjà de récupérer le code INSEE d'une ville. En jQuery par exemple :
```js
var search = 'Strasbourg';
$.getJson(
  'https://public.opendatasoft.com'
    + '/api/records/1.0/search/'
    + '?dataset=correspondance-code-insee-code-postal&q=' + search,
  function (data) {
    $('#result').html(
      'Le code INSEE de ' + result.records[0].fields.nom_comm
        + ' est ' + result.records[0].fields.insee_com
    );
  }
);
```
Démo complète :
https://jsfiddle.net/KyleKatarn/ukhhht71/1/
