### ISSUE TITLE
La ville de Carnon n'apparaît pas

### ISSUE THREAD

**Issue by Ruelov** [kylekatarnls/vicopo#8]
Bonjour,

Lors d'une recherche avec le code postal 34280, la ville de CARNON n'apparaît pas.
Pour ce code postal, il n'y a que LA GRANDE-MOTTE qui est retrouvé.

Cordialement,

**Comment by kylekatarnls** [comment]
Bonjour,

Nous fournissons l'outil de recherche mais la base de donnée utilisée est celle de opendatasoft.com (source INSEE) : https://public.opendatasoft.com/explore/dataset/correspondance-code-insee-code-postal/

Après recherche, il apparaît clairement que Carnon n'est pas une ville mais un station balnéaire appartenant à la commune de Mauguio dont le code postal est 34280 (ce que l'office de tourisme confirme : http://www.carnontourisme.com/).

Notez que des villes naissent et meurent avec leurs codes postaux, nous tenons notre base de donnée de manière automatique une fois par semaine et vous ne trouverez dans les résultats que les villes actuellement référencées officiellement comme telles.

Cordialement,

**Comment by Ruelov** [comment]
Merci pour ces informations, et votre réactivité.

Cordialement,
