### ISSUE TITLE
[feature] API add fields

### ISSUE THREAD

**Issue by alexis-landrieu-avanade** [kylekatarnls/vicopo#9]
Hello,

Can you add in your public API, the INSEE city number and gps coordinates ? You can download these data [here](https://www.data.gouv.fr/en/datasets/base-officielle-des-codes-postaux/).

**Comment by kylekatarnls** [comment]
You may be interested in #7

Vicopo aims to be light and fast. To get more data, you can use the public.opendatasoft.com API:

```js
var search = 'Strasbourg';
$.getJson(
  'https://public.opendatasoft.com'
    + '/api/records/1.0/search/'
    + '?dataset=correspondance-code-insee-code-postal&q=' + search,
  function (data) {
    $('#result').html(
      'INSEE code of ' + result.records[0].fields.nom_comm
        + ' is ' + result.records[0].fields.insee_com
    );
  }
);
```

This API also returns coordinates.
